<tables>
SELECT TABLE_NAME FROM TABLES WHERE TABLE_SCHEMA='$sdb'
</tables>

<columns>
SELECT COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE, IS_NULLABLE,
IFNULL(CHARACTER_MAXIMUM_LENGTH,-1), IFNULL(NUMERIC_PRECISION,-1)
,COLUMN_KEY,
COLUMN_COMMENT
FROM `COLUMNS`
WHERE TABLE_SCHEMA='$sdb'
AND TABLE_NAME='$stabl'
ORDER BY ORDINAL_POSITION
</columns>
