#Autogenerated in astropysics setup.py on 2010-04-14 17:25:44.479933
#these components can be changed for new versions
version = '0.1.dev-r593'

major = 0
minor = 1
bugfix = None
dev = True

release = not dev
