# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt/EyeAnalyserUI.ui'
#
# Created: Thu Apr 22 23:40:21 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(916, 601)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(250, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(-1, 12, -1, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line = QtGui.QFrame(self.frame)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.filterList = QtGui.QListWidget(self.frame)
        self.filterList.setMinimumSize(QtCore.QSize(0, 100))
        self.filterList.setMaximumSize(QtCore.QSize(16777215, 100))
        self.filterList.setObjectName("filterList")
        self.verticalLayout.addWidget(self.filterList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushFilterAdd = QtGui.QPushButton(self.frame)
        self.pushFilterAdd.setObjectName("pushFilterAdd")
        self.horizontalLayout_2.addWidget(self.pushFilterAdd)
        self.pushFilterRemove = QtGui.QPushButton(self.frame)
        self.pushFilterRemove.setObjectName("pushFilterRemove")
        self.horizontalLayout_2.addWidget(self.pushFilterRemove)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBoxLayout = QtGui.QVBoxLayout()
        self.groupBoxLayout.setObjectName("groupBoxLayout")
        self.verticalLayout.addLayout(self.groupBoxLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.radioFolder = QtGui.QRadioButton(self.frame_2)
        self.radioFolder.setObjectName("radioFolder")
        self.verticalLayout_2.addWidget(self.radioFolder)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.textFolder = QtGui.QLineEdit(self.frame_2)
        self.textFolder.setObjectName("textFolder")
        self.horizontalLayout_3.addWidget(self.textFolder)
        self.pushSelectFolder = QtGui.QPushButton(self.frame_2)
        self.pushSelectFolder.setAutoDefault(False)
        self.pushSelectFolder.setDefault(False)
        self.pushSelectFolder.setFlat(False)
        self.pushSelectFolder.setObjectName("pushSelectFolder")
        self.horizontalLayout_3.addWidget(self.pushSelectFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.radioSingle = QtGui.QRadioButton(self.frame_2)
        self.radioSingle.setObjectName("radioSingle")
        self.verticalLayout_2.addWidget(self.radioSingle)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.textSingle = QtGui.QLineEdit(self.frame_2)
        self.textSingle.setObjectName("textSingle")
        self.horizontalLayout_4.addWidget(self.textSingle)
        self.pushSelectSingle = QtGui.QPushButton(self.frame_2)
        self.pushSelectSingle.setObjectName("pushSelectSingle")
        self.horizontalLayout_4.addWidget(self.pushSelectSingle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.radioCurrent = QtGui.QRadioButton(self.frame_2)
        self.radioCurrent.setObjectName("radioCurrent")
        self.verticalLayout_2.addWidget(self.radioCurrent)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.line_3 = QtGui.QFrame(self.frame_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.metricList = QtGui.QListWidget(self.frame_3)
        self.metricList.setMinimumSize(QtCore.QSize(0, 100))
        self.metricList.setMaximumSize(QtCore.QSize(16777215, 100))
        self.metricList.setObjectName("metricList")
        self.verticalLayout_3.addWidget(self.metricList)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushMetricAdd = QtGui.QPushButton(self.frame_3)
        self.pushMetricAdd.setObjectName("pushMetricAdd")
        self.horizontalLayout_6.addWidget(self.pushMetricAdd)
        self.pushMetricRemove = QtGui.QPushButton(self.frame_3)
        self.pushMetricRemove.setObjectName("pushMetricRemove")
        self.horizontalLayout_6.addWidget(self.pushMetricRemove)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushOpenStudio = QtGui.QPushButton(self.centralwidget)
        self.pushOpenStudio.setObjectName("pushOpenStudio")
        self.horizontalLayout_5.addWidget(self.pushOpenStudio)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.pushAnalyse = QtGui.QPushButton(self.centralwidget)
        self.pushAnalyse.setObjectName("pushAnalyse")
        self.horizontalLayout_5.addWidget(self.pushAnalyse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 916, 22))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Eye Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Step 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Choose algorithms", None, QtGui.QApplication.UnicodeUTF8))
        self.pushFilterAdd.setText(QtGui.QApplication.translate("mainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushFilterRemove.setText(QtGui.QApplication.translate("mainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Step 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Choose data files", None, QtGui.QApplication.UnicodeUTF8))
        self.radioFolder.setText(QtGui.QApplication.translate("mainWindow", "Folder of NPZ files", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSelectFolder.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.radioSingle.setText(QtGui.QApplication.translate("mainWindow", "Single NPZ file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushSelectSingle.setText(QtGui.QApplication.translate("mainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.radioCurrent.setText(QtGui.QApplication.translate("mainWindow", "Currently opened data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "Step 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("mainWindow", "Choose metrics", None, QtGui.QApplication.UnicodeUTF8))
        self.pushMetricAdd.setText(QtGui.QApplication.translate("mainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushMetricRemove.setText(QtGui.QApplication.translate("mainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushOpenStudio.setText(QtGui.QApplication.translate("mainWindow", "Return to Eye Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.pushAnalyse.setText(QtGui.QApplication.translate("mainWindow", "Analyse", None, QtGui.QApplication.UnicodeUTF8))

