# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQt/EyeStudioUI.ui'
#
# Created: Thu Apr 22 23:40:21 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.resize(980, 531)
        mainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(320, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabMenu = QtGui.QTabWidget(self.frame)
        self.tabMenu.setObjectName("tabMenu")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.filterList = QtGui.QListWidget(self.tab)
        self.filterList.setMaximumSize(QtCore.QSize(16777215, 120))
        self.filterList.setObjectName("filterList")
        self.verticalLayout_4.addWidget(self.filterList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loadButton = QtGui.QPushButton(self.tab)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_2.addWidget(self.loadButton)
        self.unloadButton = QtGui.QPushButton(self.tab)
        self.unloadButton.setObjectName("unloadButton")
        self.horizontalLayout_2.addWidget(self.unloadButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBoxLayout = QtGui.QVBoxLayout()
        self.groupBoxLayout.setObjectName("groupBoxLayout")
        self.verticalLayout_4.addLayout(self.groupBoxLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.pushOpenAnalyser = QtGui.QPushButton(self.tab)
        self.pushOpenAnalyser.setObjectName("pushOpenAnalyser")
        self.verticalLayout_4.addWidget(self.pushOpenAnalyser)
        self.tabMenu.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.setSelection = QtGui.QPushButton(self.tab_2)
        self.setSelection.setObjectName("setSelection")
        self.gridLayout.addWidget(self.setSelection, 0, 1, 1, 1)
        self.labelList = QtGui.QComboBox(self.tab_2)
        self.labelList.setObjectName("labelList")
        self.gridLayout.addWidget(self.labelList, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.checkBoxZoom = QtGui.QCheckBox(self.tab_2)
        self.checkBoxZoom.setObjectName("checkBoxZoom")
        self.verticalLayout_5.addWidget(self.checkBoxZoom)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.importAnalysedDialog = QtGui.QPushButton(self.tab_2)
        self.importAnalysedDialog.setObjectName("importAnalysedDialog")
        self.verticalLayout_5.addWidget(self.importAnalysedDialog)
        self.tabMenu.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabMenu)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvasLayout = QtGui.QGridLayout()
        self.canvasLayout.setObjectName("canvasLayout")
        self.verticalLayout_2.addLayout(self.canvasLayout)
        self.labellingCanvasFrame = QtGui.QFrame(self.centralwidget)
        self.labellingCanvasFrame.setMinimumSize(QtCore.QSize(0, 130))
        self.labellingCanvasFrame.setMaximumSize(QtCore.QSize(16777215, 130))
        self.labellingCanvasFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.labellingCanvasFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.labellingCanvasFrame.setLineWidth(0)
        self.labellingCanvasFrame.setObjectName("labellingCanvasFrame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.labellingCanvasFrame)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labellingCanvasLayout = QtGui.QGridLayout()
        self.labellingCanvasLayout.setObjectName("labellingCanvasLayout")
        self.horizontalLayout_4.addLayout(self.labellingCanvasLayout)
        self.verticalLayout_2.addWidget(self.labellingCanvasFrame)
        self.timeBarFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeBarFrame.sizePolicy().hasHeightForWidth())
        self.timeBarFrame.setSizePolicy(sizePolicy)
        self.timeBarFrame.setMaximumSize(QtCore.QSize(16777215, 45))
        self.timeBarFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.timeBarFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.timeBarFrame.setLineWidth(0)
        self.timeBarFrame.setObjectName("timeBarFrame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.timeBarFrame)
        self.horizontalLayout_3.setSpacing(-1)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.timeLabel = QtGui.QLabel(self.timeBarFrame)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.timeBar = QtGui.QSlider(self.timeBarFrame)
        self.timeBar.setOrientation(QtCore.Qt.Horizontal)
        self.timeBar.setObjectName("timeBar")
        self.horizontalLayout_3.addWidget(self.timeBar)
        self.playButton = QtGui.QPushButton(self.timeBarFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(42, 42))
        self.playButton.setMaximumSize(QtCore.QSize(42, 42))
        self.playButton.setAutoFillBackground(False)
        self.playButton.setDefault(False)
        self.playButton.setFlat(True)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_3.addWidget(self.playButton)
        self.verticalLayout_2.addWidget(self.timeBarFrame)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.errorConsoleFrame = QtGui.QFrame(self.centralwidget)
        self.errorConsoleFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.errorConsoleFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.errorConsoleFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.errorConsoleFrame.setObjectName("errorConsoleFrame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.errorConsoleFrame)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.errorConsole = QtGui.QTextEdit(self.errorConsoleFrame)
        self.errorConsole.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorConsole.setFont(font)
        self.errorConsole.setObjectName("errorConsole")
        self.verticalLayout_3.addWidget(self.errorConsole)
        self.horizontalLayout.addWidget(self.errorConsoleFrame)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Settings = QtGui.QMenu(self.menubar)
        self.menu_Settings.setObjectName("menu_Settings")
        self.menuControl = QtGui.QMenu(self.menubar)
        self.menuControl.setObjectName("menuControl")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action_open = QtGui.QAction(mainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtGui.QAction(mainWindow)
        self.action_save.setObjectName("action_save")
        self.action_importTSV = QtGui.QAction(mainWindow)
        self.action_importTSV.setObjectName("action_importTSV")
        self.action_showHideErrorConsole = QtGui.QAction(mainWindow)
        self.action_showHideErrorConsole.setObjectName("action_showHideErrorConsole")
        self.action_step1minus = QtGui.QAction(mainWindow)
        self.action_step1minus.setVisible(True)
        self.action_step1minus.setPriority(QtGui.QAction.NormalPriority)
        self.action_step1minus.setObjectName("action_step1minus")
        self.action_step1plus = QtGui.QAction(mainWindow)
        self.action_step1plus.setObjectName("action_step1plus")
        self.action_step5minus = QtGui.QAction(mainWindow)
        self.action_step5minus.setObjectName("action_step5minus")
        self.action_step5plus = QtGui.QAction(mainWindow)
        self.action_step5plus.setObjectName("action_step5plus")
        self.action_startSelection = QtGui.QAction(mainWindow)
        self.action_startSelection.setObjectName("action_startSelection")
        self.action_deselect = QtGui.QAction(mainWindow)
        self.action_deselect.setObjectName("action_deselect")
        self.action_saveAs = QtGui.QAction(mainWindow)
        self.action_saveAs.setObjectName("action_saveAs")
        self.action_importStimulus = QtGui.QAction(mainWindow)
        self.action_importStimulus.setObjectName("action_importStimulus")
        self.action_showHideOrdinals = QtGui.QAction(mainWindow)
        self.action_showHideOrdinals.setObjectName("action_showHideOrdinals")
        self.action_showHideTimeline = QtGui.QAction(mainWindow)
        self.action_showHideTimeline.setObjectName("action_showHideTimeline")
        self.menu_File.addAction(self.action_open)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_save)
        self.menu_File.addAction(self.action_saveAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_importTSV)
        self.menu_File.addAction(self.action_importStimulus)
        self.menu_Settings.addAction(self.action_showHideErrorConsole)
        self.menu_Settings.addAction(self.action_showHideOrdinals)
        self.menu_Settings.addAction(self.action_showHideTimeline)
        self.menuControl.addAction(self.action_step1minus)
        self.menuControl.addAction(self.action_step1plus)
        self.menuControl.addAction(self.action_step5minus)
        self.menuControl.addAction(self.action_step5plus)
        self.menuControl.addSeparator()
        self.menuControl.addAction(self.action_startSelection)
        self.menuControl.addAction(self.action_deselect)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menubar.addAction(self.menu_Settings.menuAction())

        self.retranslateUi(mainWindow)
        self.tabMenu.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "Eye Studio", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Algorithms (Filters):", None, QtGui.QApplication.UnicodeUTF8))
        self.loadButton.setText(QtGui.QApplication.translate("mainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.unloadButton.setText(QtGui.QApplication.translate("mainWindow", "Unload", None, QtGui.QApplication.UnicodeUTF8))
        self.pushOpenAnalyser.setText(QtGui.QApplication.translate("mainWindow", "Open Eye Analyser", None, QtGui.QApplication.UnicodeUTF8))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab), QtGui.QApplication.translate("mainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Press Ctrl+D to start a selection, then use the arrow keys to make a selection.", None, QtGui.QApplication.UnicodeUTF8))
        self.setSelection.setText(QtGui.QApplication.translate("mainWindow", "Set selection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxZoom.setText(QtGui.QApplication.translate("mainWindow", "Centre data and zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.importAnalysedDialog.setText(QtGui.QApplication.translate("mainWindow", "Copy from analysed data...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabMenu.setTabText(self.tabMenu.indexOf(self.tab_2), QtGui.QApplication.translate("mainWindow", "Labelling", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("mainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("mainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Settings.setTitle(QtGui.QApplication.translate("mainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.menuControl.setTitle(QtGui.QApplication.translate("mainWindow", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("mainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setStatusTip(QtGui.QApplication.translate("mainWindow", "Open NPZ data file.", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setText(QtGui.QApplication.translate("mainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_importTSV.setText(QtGui.QApplication.translate("mainWindow", "&Import TSV file...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_importTSV.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+I", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showHideErrorConsole.setText(QtGui.QApplication.translate("mainWindow", "Show/hide &Error Console", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showHideErrorConsole.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.action_step1minus.setText(QtGui.QApplication.translate("mainWindow", "Step backwards", None, QtGui.QApplication.UnicodeUTF8))
        self.action_step1minus.setShortcut(QtGui.QApplication.translate("mainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.action_step1plus.setText(QtGui.QApplication.translate("mainWindow", "Step forwards", None, QtGui.QApplication.UnicodeUTF8))
        self.action_step1plus.setShortcut(QtGui.QApplication.translate("mainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.action_step5minus.setText(QtGui.QApplication.translate("mainWindow", "Step 5 backwards", None, QtGui.QApplication.UnicodeUTF8))
        self.action_step5plus.setText(QtGui.QApplication.translate("mainWindow", "Step 5 forwards", None, QtGui.QApplication.UnicodeUTF8))
        self.action_startSelection.setText(QtGui.QApplication.translate("mainWindow", "Start selection", None, QtGui.QApplication.UnicodeUTF8))
        self.action_startSelection.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.action_deselect.setText(QtGui.QApplication.translate("mainWindow", "Deselect", None, QtGui.QApplication.UnicodeUTF8))
        self.action_deselect.setShortcut(QtGui.QApplication.translate("mainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveAs.setText(QtGui.QApplication.translate("mainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveAs.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_importStimulus.setText(QtGui.QApplication.translate("mainWindow", "Import Stimulus file...", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showHideOrdinals.setText(QtGui.QApplication.translate("mainWindow", "Show/hide Label Ordinals", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showHideOrdinals.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showHideTimeline.setText(QtGui.QApplication.translate("mainWindow", "Show/hide Timeline", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showHideTimeline.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))

