/* Generated by Pyrex 0.9.8.5 on Fri May 21 13:14:18 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "stdio.h"
#include "ctype.h"
#include "string.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from pygr.seqfmt */


/* Declarations from implementation of pygr.seqfmt */


static char __pyx_k1[] = "fileno";
static char __pyx_k2[] = "r";
static char __pyx_k3[] = "unable to open %s";
static char __pyx_k4[] = ".pureseq";
static char __pyx_k5[] = "wb";
static char __pyx_k6[] = "unable to create %s";
static char __pyx_k7[] = ">";
static char __pyx_k8[] = "split";

static PyObject *__pyx_n_fileno;
static PyObject *__pyx_n_split;

static PyObject *__pyx_k3p;
static PyObject *__pyx_k4p;
static PyObject *__pyx_k6p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n_fileno, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_split, 1, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k3p, 0, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k6p, 0, __pyx_k6, sizeof(__pyx_k6)},
  {0, 0, 0, 0}
};



/* Implementation of pygr.seqfmt */

static PyObject *__pyx_f_4pygr_6seqfmt_read_fasta_lengths(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_4pygr_6seqfmt_read_fasta_lengths[] = "read seq lengths from python file object, save into dictionary d";
static PyObject *__pyx_f_4pygr_6seqfmt_read_fasta_lengths(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_d = 0;
  PyObject *__pyx_v_pyfile = 0;
  PyObject *__pyx_v_filename = 0;
  int __pyx_v_i;
  PY_LONG_LONG __pyx_v_seqLength;
  PY_LONG_LONG __pyx_v_ipos;
  PY_LONG_LONG __pyx_v_offset;
  char __pyx_v_tmp[32768];
  char __pyx_v_fastastart[4];
  char *__pyx_v_p;
  FILE *__pyx_v_ifile;
  FILE *__pyx_v_ifile2;
  PyObject *__pyx_v_outfile;
  PyObject *__pyx_v_id;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  int __pyx_3;
  char *__pyx_4;
  PyObject *__pyx_5 = 0;
  char __pyx_6;
  static char *__pyx_argnames[] = {"d","pyfile","filename",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_d, &__pyx_v_pyfile, &__pyx_v_filename)) return 0;
  Py_INCREF(__pyx_v_d);
  Py_INCREF(__pyx_v_pyfile);
  Py_INCREF(__pyx_v_filename);
  __pyx_v_outfile = Py_None; Py_INCREF(Py_None);
  __pyx_v_id = Py_None; Py_INCREF(Py_None);

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":28 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_pyfile, __pyx_n_fileno); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_AsLong(__pyx_2); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_v_ifile = fdopen(__pyx_3,__pyx_k2);

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":29 */
  __pyx_3 = (__pyx_v_ifile == NULL);
  if (__pyx_3) {
    __pyx_1 = PyNumber_Remainder(__pyx_k3p, __pyx_v_filename); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
    __pyx_1 = 0;
    __pyx_1 = PyObject_CallObject(PyExc_IOError, __pyx_2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    __Pyx_Raise(__pyx_1, 0, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":31 */
  __pyx_2 = PyNumber_Add(__pyx_v_filename, __pyx_k4p); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; goto __pyx_L1;}
  Py_DECREF(__pyx_v_outfile);
  __pyx_v_outfile = __pyx_2;
  __pyx_2 = 0;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":33 */
  __pyx_4 = PyString_AsString(__pyx_v_outfile); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; goto __pyx_L1;}
  __pyx_v_ifile2 = fopen(__pyx_4,__pyx_k5);

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":34 */
  __pyx_3 = (__pyx_v_ifile2 == NULL);
  if (__pyx_3) {
    __pyx_1 = PyNumber_Add(__pyx_v_filename, __pyx_k4p); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
    __pyx_2 = PyNumber_Remainder(__pyx_k6p, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __pyx_1 = PyTuple_New(1); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_1, 0, __pyx_2);
    __pyx_2 = 0;
    __pyx_2 = PyObject_CallObject(PyExc_IOError, __pyx_1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    __Pyx_Raise(__pyx_2, 0, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":36 */
  Py_INCREF(Py_None);
  Py_DECREF(__pyx_v_id);
  __pyx_v_id = Py_None;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":37 */
  __pyx_v_ipos = 0;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":38 */
  __pyx_v_seqLength = 0;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":39 */
  strcpy(__pyx_v_fastastart,__pyx_k7);

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":40 */
  __pyx_v_p = fgets(__pyx_v_tmp,32767,__pyx_v_ifile);

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":41 */
  while (1) {
    __pyx_3 = (__pyx_v_p != 0);
    if (!__pyx_3) break;

    /* "/result/mareks/pygr/pygr/seqfmt.pyx":42 */
    __pyx_3 = ((__pyx_v_fastastart[0]) == (__pyx_v_p[0]));
    if (__pyx_3) {

      /* "/result/mareks/pygr/pygr/seqfmt.pyx":43 */
      __pyx_3 = __pyx_v_id != Py_None;
      if (__pyx_3) {
        __pyx_3 = (__pyx_v_seqLength > 0);
      }
      if (__pyx_3) {
        __pyx_1 = PyLong_FromLongLong(__pyx_v_seqLength); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
        __pyx_2 = PyLong_FromLongLong(__pyx_v_offset); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
        __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
        PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
        PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
        __pyx_1 = 0;
        __pyx_2 = 0;
        if (PyObject_SetItem(__pyx_v_d, __pyx_v_id, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; goto __pyx_L1;}
        Py_DECREF(__pyx_5); __pyx_5 = 0;
        goto __pyx_L7;
      }
      __pyx_L7:;

      /* "/result/mareks/pygr/pygr/seqfmt.pyx":45 */
      __pyx_1 = PyString_FromString((__pyx_v_p + 1)); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
      __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
      PyTuple_SET_ITEM(__pyx_2, 0, __pyx_1);
      __pyx_1 = 0;
      __pyx_5 = PyObject_CallObject(((PyObject *)(&PyString_Type)), __pyx_2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      __pyx_1 = PyObject_GetAttr(__pyx_5, __pyx_n_split); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
      Py_DECREF(__pyx_5); __pyx_5 = 0;
      __pyx_2 = PyObject_CallObject(__pyx_1, 0); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
      Py_DECREF(__pyx_1); __pyx_1 = 0;
      __pyx_5 = __Pyx_GetItemInt(__pyx_2, 0); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; goto __pyx_L1;}
      Py_DECREF(__pyx_2); __pyx_2 = 0;
      Py_DECREF(__pyx_v_id);
      __pyx_v_id = __pyx_5;
      __pyx_5 = 0;

      /* "/result/mareks/pygr/pygr/seqfmt.pyx":46 */
      __pyx_v_offset = __pyx_v_ipos;

      /* "/result/mareks/pygr/pygr/seqfmt.pyx":47 */
      __pyx_v_seqLength = 0;
      goto __pyx_L6;
    }
    /*else*/ {

      /* "/result/mareks/pygr/pygr/seqfmt.pyx":49 */
      __pyx_v_i = 0;

      /* "/result/mareks/pygr/pygr/seqfmt.pyx":50 */
      while (1) {
        __pyx_6 = (__pyx_v_p[__pyx_v_i]);
        if (!__pyx_6) break;

        /* "/result/mareks/pygr/pygr/seqfmt.pyx":51 */
        __pyx_3 = isprint((__pyx_v_p[__pyx_v_i]));
        if (__pyx_3) {
          __pyx_3 = (!isspace((__pyx_v_p[__pyx_v_i])));
        }
        if (__pyx_3) {

          /* "/result/mareks/pygr/pygr/seqfmt.pyx":52 */
          __pyx_v_seqLength = (__pyx_v_seqLength + 1);

          /* "/result/mareks/pygr/pygr/seqfmt.pyx":53 */
          fputc((__pyx_v_p[__pyx_v_i]),__pyx_v_ifile2);

          /* "/result/mareks/pygr/pygr/seqfmt.pyx":54 */
          __pyx_v_ipos = (__pyx_v_ipos + 1);
          goto __pyx_L10;
        }
        __pyx_L10:;

        /* "/result/mareks/pygr/pygr/seqfmt.pyx":55 */
        __pyx_v_i = (__pyx_v_i + 1);
      }
    }
    __pyx_L6:;

    /* "/result/mareks/pygr/pygr/seqfmt.pyx":56 */
    __pyx_v_p = fgets(__pyx_v_tmp,32767,__pyx_v_ifile);
  }

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":57 */
  __pyx_3 = __pyx_v_id != Py_None;
  if (__pyx_3) {
    __pyx_3 = (__pyx_v_seqLength > 0);
  }
  if (__pyx_3) {
    __pyx_1 = PyLong_FromLongLong(__pyx_v_seqLength); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_2 = PyLong_FromLongLong(__pyx_v_offset); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_1);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_2);
    __pyx_1 = 0;
    __pyx_2 = 0;
    if (PyObject_SetItem(__pyx_v_d, __pyx_v_id, __pyx_5) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; goto __pyx_L1;}
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    goto __pyx_L11;
  }
  __pyx_L11:;

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":59 */
  fclose(__pyx_v_ifile2);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("pygr.seqfmt.read_fasta_lengths");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_outfile);
  Py_DECREF(__pyx_v_id);
  Py_DECREF(__pyx_v_d);
  Py_DECREF(__pyx_v_pyfile);
  Py_DECREF(__pyx_v_filename);
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"read_fasta_lengths", (PyCFunction)__pyx_f_4pygr_6seqfmt_read_fasta_lengths, METH_VARARGS|METH_KEYWORDS, __pyx_doc_4pygr_6seqfmt_read_fasta_lengths},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initseqfmt(void); /*proto*/
PyMODINIT_FUNC initseqfmt(void) {
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("seqfmt", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; goto __pyx_L1;};

  /* "/result/mareks/pygr/pygr/seqfmt.pyx":21 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("pygr.seqfmt");
}

static char *__pyx_filenames[] = {
  "seqfmt.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static PyObject *__Pyx_GetItemInt(PyObject *o, Py_ssize_t i) {
    PyTypeObject *t = o->ob_type;
    PyObject *r;
    if (t->tp_as_sequence && t->tp_as_sequence->sq_item)
        r = PySequence_GetItem(o, i);
    else {
        PyObject *j = PyInt_FromLong(i);
        if (!j)
            return 0;
        r = PyObject_GetItem(o, j);
        Py_DECREF(j);
    }
    return r;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
