/*
DO NOT EDIT!

This file is autogenerated by setup.py.  To edit its contents,
edit doc/docstrings.py
*/

#ifndef __DOCSTRINGS_H__
#define __DOCSTRINGS_H__

void fill_docstrings(void);

extern char doc_DistortionLookupTable[370];
extern char doc_K[153];
extern char doc_M[57];
extern char doc_Sip[1018];
extern char doc_Tabprm[227];
extern char doc_UnitConverter[2217];
extern char doc_Wcs[483];
extern char doc_Wcsprm[1980];
extern char doc_Wtbarr[196];
extern char doc_a[223];
extern char doc_a_order[95];
extern char doc_all_pix2sky[1205];
extern char doc_alt[237];
extern char doc_ap[226];
extern char doc_ap_order[97];
extern char doc_axis_types[917];
extern char doc_b[223];
extern char doc_b_order[95];
extern char doc_bp[226];
extern char doc_bp_order[97];
extern char doc_cd[1100];
extern char doc_cdelt[303];
extern char doc_cel_offset[154];
extern char doc_celfix[137];
extern char doc_cname[77];
extern char doc_colax[92];
extern char doc_colnum[236];
extern char doc_convert[121];
extern char doc_coord[279];
extern char doc_copy[40];
extern char doc_cpdis1[100];
extern char doc_cpdis2[100];
extern char doc_crder[124];
extern char doc_crota[229];
extern char doc_crpix[89];
extern char doc_crval[94];
extern char doc_crval_tabprm[132];
extern char doc_csyer[133];
extern char doc_ctype[223];
extern char doc_cubeface[1210];
extern char doc_cunit[1202];
extern char doc_cylfix[128];
extern char doc_data[73];
extern char doc_data_wtbarr[52];
extern char doc_dateavg[147];
extern char doc_dateobs[128];
extern char doc_datfix[454];
extern char doc_delta[196];
extern char doc_det2im[58];
extern char doc_det2im1[97];
extern char doc_det2im2[97];
extern char doc_dims[99];
extern char doc_equinox[243];
extern char doc_extlev[73];
extern char doc_extnam[74];
extern char doc_extrema[440];
extern char doc_extver[73];
extern char doc_find_all_wcs[847];
extern char doc_fix[1383];
extern char doc_get_offset[104];
extern char doc_get_ps[364];
extern char doc_get_pv[648];
extern char doc_has_cd[860];
extern char doc_has_cdi_ja[97];
extern char doc_has_crota[615];
extern char doc_has_crotaia[102];
extern char doc_has_pc[177];
extern char doc_has_pci_ja[97];
extern char doc_i[41];
extern char doc_imgpix_matrix[144];
extern char doc_is_unity[103];
extern char doc_kind[130];
extern char doc_lat[90];
extern char doc_latpole[76];
extern char doc_lattyp[228];
extern char doc_lng[91];
extern char doc_lngtyp[229];
extern char doc_lonpole[77];
extern char doc_m[59];
extern char doc_map[942];
extern char doc_mix[4643];
extern char doc_mjdavg[190];
extern char doc_mjdobs[190];
extern char doc_name[75];
extern char doc_naxis[761];
extern char doc_nc[122];
extern char doc_ndim[67];
extern char doc_obsgeo[187];
extern char doc_offset[48];
extern char doc_p0[197];
extern char doc_p2s[1822];
extern char doc_p4_pix2foc[557];
extern char doc_pc[423];
extern char doc_phi0[284];
extern char doc_pix2foc[559];
extern char doc_piximg_matrix[129];
extern char doc_power[50];
extern char doc_print_contents[205];
extern char doc_print_contents_tabprm[211];
extern char doc_radesys[78];
extern char doc_restfrq[95];
extern char doc_restwav[95];
extern char doc_row[40];
extern char doc_s2p[1711];
extern char doc_scale[57];
extern char doc_sense[183];
extern char doc_set[1179];
extern char doc_set_ps[355];
extern char doc_set_pv[355];
extern char doc_set_tabprm[347];
extern char doc_sip[78];
extern char doc_sip_foc2pix[574];
extern char doc_sip_pix2foc[572];
extern char doc_spcfix[238];
extern char doc_spec[69];
extern char doc_specsys[140];
extern char doc_sptr[1355];
extern char doc_ssysobs[227];
extern char doc_ssyssrc[111];
extern char doc_sub[3097];
extern char doc_tab[84];
extern char doc_theta0[283];
extern char doc_to_header[2087];
extern char doc_ttype[108];
extern char doc_unitfix[1009];
extern char doc_velangl[170];
extern char doc_velosys[283];
extern char doc_wcs[76];
extern char doc_zsource[99];

#endif

