
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '-*\xa7\x0e\xa8C\x08P\xa5\xbd\x02\x8e\x8d\xdc{\x85'
    
_lr_action_items = {'false':([35,47,],[38,38,]),'JDSWINGOBJECT':([8,14,18,28,31,33,37,43,46,48,],[15,15,-6,-3,-5,-4,-7,15,-8,15,]),'TEXT':([35,47,],[40,40,]),'SYMBOL':([2,10,26,29,30,34,36,38,39,40,41,42,43,44,45,49,50,51,52,53,],[3,27,27,-22,27,-21,27,-33,-27,-31,-30,-29,27,-32,-23,27,-24,-28,-26,-25,]),'GLOBAL':([4,5,],[7,7,]),'JDELLIPSE':([8,14,18,28,31,33,37,43,46,48,],[17,17,-6,-3,-5,-4,-7,17,-8,17,]),'LBRACKET':([2,3,7,11,12,13,15,16,17,19,20,21,22,23,24,25,35,],[4,5,10,-16,30,-10,-15,-12,-13,-17,-11,-18,-19,-14,-20,-9,43,]),'JDPOLYLINE':([8,14,18,28,31,33,37,43,46,48,],[19,19,-6,-3,-5,-4,-7,19,-8,19,]),'JDROUNDRECTANGLE':([8,14,18,28,31,33,37,43,46,48,],[20,20,-6,-3,-5,-4,-7,20,-8,20,]),'JDIMAGE':([8,14,18,28,31,33,37,43,46,48,],[21,21,-6,-3,-5,-4,-7,21,-8,21,]),'JDAXIS':([8,14,18,28,31,33,37,43,46,48,],[22,22,-6,-3,-5,-4,-7,22,-8,22,]),'JDLINE':([8,14,18,28,31,33,37,43,46,48,],[25,25,-6,-3,-5,-4,-7,25,-8,25,]),'JDGROUP':([8,14,18,28,31,33,37,43,46,48,],[16,16,-6,-3,-5,-4,-7,16,-8,16,]),'COMMA':([38,39,40,41,42,44,51,],[-33,47,-31,-30,-29,-32,-28,]),'JDBAR':([8,14,18,28,31,33,37,43,46,48,],[23,23,-6,-3,-5,-4,-7,23,-8,23,]),'JDSLIDER':([8,14,18,28,31,33,37,43,46,48,],[24,24,-6,-3,-5,-4,-7,24,-8,24,]),'$end':([1,9,32,],[0,-2,-1,]),'JDLABEL':([8,14,18,28,31,33,37,43,46,48,],[11,11,-6,-3,-5,-4,-7,11,-8,11,]),'NUMBER':([35,47,],[41,41,]),'true':([35,47,],[44,44,]),'JDRECTANGLE':([8,14,18,28,31,33,37,43,46,48,],[13,13,-6,-3,-5,-4,-7,13,-8,13,]),'JDFILE':([0,],[2,]),'RBRACKET':([6,10,14,18,26,28,29,30,31,33,34,36,37,38,39,40,41,42,43,44,45,46,48,49,50,51,52,53,],[9,28,32,-6,33,-3,-22,37,-5,-4,-21,46,-7,-33,-27,-31,-30,-29,50,-32,-23,-8,52,53,-24,-28,-26,-25,]),'TWOP':([27,],[35,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'obj':([8,14,43,48,],[12,12,12,12,]),'parameter_list':([10,30,43,],[26,36,49,]),'element_list':([8,43,],[14,48,]),'value_list':([35,],[39,]),'global':([4,5,],[6,8,]),'value':([35,47,],[42,51,]),'element':([8,14,43,48,],[18,31,18,31,]),'param_value':([35,],[45,]),'parameter':([10,26,30,36,43,49,],[29,34,29,34,29,34,]),'jdfile':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> jdfile","S'",1,None,None,None),
  ('jdfile -> JDFILE SYMBOL LBRACKET global element_list RBRACKET','jdfile',6,'p_jdfile','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',106),
  ('jdfile -> JDFILE LBRACKET global RBRACKET','jdfile',4,'p_jdfile_empty','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',114),
  ('global -> GLOBAL LBRACKET RBRACKET','global',3,'p_global','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',122),
  ('global -> GLOBAL LBRACKET parameter_list RBRACKET','global',4,'p_global','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',123),
  ('element_list -> element_list element','element_list',2,'p_element_list','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',130),
  ('element_list -> element','element_list',1,'p_element','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',137),
  ('element -> obj LBRACKET RBRACKET','element',3,'p_single_element','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',141),
  ('element -> obj LBRACKET parameter_list RBRACKET','element',4,'p_single_element','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',142),
  ('obj -> JDLINE','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',186),
  ('obj -> JDRECTANGLE','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',187),
  ('obj -> JDROUNDRECTANGLE','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',188),
  ('obj -> JDGROUP','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',189),
  ('obj -> JDELLIPSE','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',190),
  ('obj -> JDBAR','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',191),
  ('obj -> JDSWINGOBJECT','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',192),
  ('obj -> JDLABEL','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',193),
  ('obj -> JDPOLYLINE','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',194),
  ('obj -> JDIMAGE','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',195),
  ('obj -> JDAXIS','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',196),
  ('obj -> JDSLIDER','obj',1,'p_obj','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',197),
  ('parameter_list -> parameter_list parameter','parameter_list',2,'p_parameter_list','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',201),
  ('parameter_list -> parameter','parameter_list',1,'p_parameter','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',206),
  ('parameter -> SYMBOL TWOP param_value','parameter',3,'p_single_parameter','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',210),
  ('parameter -> SYMBOL TWOP LBRACKET RBRACKET','parameter',4,'p_complex_parameter','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',219),
  ('parameter -> SYMBOL TWOP LBRACKET parameter_list RBRACKET','parameter',5,'p_complex_parameter','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',220),
  ('parameter -> SYMBOL TWOP LBRACKET element_list RBRACKET','parameter',5,'p_complex_parameter','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',221),
  ('param_value -> value_list','param_value',1,'p_param_value_number_list','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',229),
  ('value_list -> value_list COMMA value','value_list',3,'p_value_list','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',236),
  ('value_list -> value','value_list',1,'p_value_list_value','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',240),
  ('value -> NUMBER','value',1,'p_value_number','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',244),
  ('value -> TEXT','value',1,'p_value_text','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',248),
  ('value -> true','value',1,'p_value_bool','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',252),
  ('value -> false','value',1,'p_value_bool','/home/tcoutinho/workspace/taurus/lib/taurus/qt/qtgui/graphic/jdraw/jdraw_parser.py',253),
]
