from AccessControl import allow_module

from Products.Archetypes import atapi

# BBB pake the ATCountry widget unpickleable
import sys
import Products.Archetypes
from Products.Archetypes import Widget
sys.modules['Products.ATCountryWidget'] = Products.Archetypes
sys.modules['Products.ATCountryWidget.Widget'] = Widget
Widget.CountryWidget = Widget.SelectionWidget

module = "Products.PloneServicesCenter.content.country"
allow_module(module)

countries = {
    "Europe (Western)": atapi.DisplayList([
        ("ad", "Andorra"),
        ("at", "Austria"),
        ("be", "Belgium"),
        ("dk", "Denmark"),
        ("fo", "Faroe Islands"),
        ("fi", "Finland"),
        ("fr", "France"),
        ("de", "Germany"),
        ("gi", "Gibraltar"),
        ("gl", "Greenland"),
        ("is", "Iceland"),
        ("ie", "Ireland"),
        ("it", "Italy"),
        ("li", "Liechtenstein"),
        ("lu", "Luxembourg"),
        ("mt", "Malta"),
        ("mc", "Monaco"),
        ("nl", "Netherlands"),
        ("no", "Norway"),
        ("pt", "Portugal"),
        ("sm", "San Marino"),
        ("es", "Spain"),
        ("sj", "Svalbard And Jan Mayen Islands"),
        ("se", "Sweden"),
        ("ch", "Switzerland"),
        ("gb", "United Kingdom"),
        ("va", "Vatican City State (Holy See)"),
        ]),
    "Europe (Central)": atapi.DisplayList([
        ("al", "Albania"),
        ("ba", "Bosnia And Herzegowina"),
        ("bg", "Bulgaria"),
        ("hr", "Croatia (Local Name: Hrvatska)"),
        ("cz", "Czech Republic"),
        ("gr", "Greece"),
        ("hu", "Hungary"),
        ("mk", "Macedonia, The Former Yugoslav Republic Of"),
        ("pl", "Poland"),
        ("ro", "Romania"),
        ("cs", "Serbia"),
        ("sk", "Slovakia (Slovak Republic)"),
        ("si", "Slovenia"),
        ]),
    "Europe (Eastern)": atapi.DisplayList([
        ("am", "Armenia"),
        ("az", "Azerbaijan"),
        ("by", "Belarus"),
        ("ee", "Estonia"),
        ("ge", "Georgia"),
        ("lv", "Latvia"),
        ("lt", "Lithuania"),
        ("md", "Moldova, Republic Of"),
        ("ru", "Russian Federation"),
        ("ua", "Ukraine"),
        ]),
    "North America": atapi.DisplayList([
        ("ca", "Canada"),
        ("mx", "Mexico"),
        ("pm", "St. Pierre And Miquelon"),
        ("us", "United States"),
        ("um", "United States Minor Outlying Islands"),
        ]),
    "Central America": atapi.DisplayList([
        ("bz", "Belize"),
        ("cr", "Costa Rica"),
        ("sv", "El Salvador"),
        ("gt", "Guatemala"),
        ("hn", "Honduras"),
        ("ni", "Nicaragua"),
        ("pa", "Panama"),
        ]),
    "South America": atapi.DisplayList([
        ("ar", "Argentina"),
        ("bo", "Bolivia"),
        ("br", "Brazil"),
        ("cl", "Chile"),
        ("co", "Colombia"),
        ("ec", "Ecuador"),
        ("fk", "Falkland Islands (Malvinas)"),
        ("gf", "French Guiana"),
        ("gy", "Guyana"),
        ("py", "Paraguay"),
        ("pe", "Peru"),
        ("gs", "South Georgia And The South Sandwich Islands"),
        ("sr", "Suriname"),
        ("uy", "Uruguay"),
        ("ve", "Venezuela"),
        ]),
    "Middle East": atapi.DisplayList([
        ("bh", "Bahrain"),
        ("cy", "Cyprus"),
        ("ir", "Iran (Islamic Republic Of)"),
        ("iq", "Iraq"),
        ("il", "Israel"),
        ("jo", "Jordan"),
        ("kw", "Kuwait"),
        ("lb", "Lebanon"),
        ("om", "Oman"),
        ("qa", "Qatar"),
        ("sa", "Saudi Arabia"),
        ("sy", "Syrian Arab Republic"),
        ("tr", "Turkey"),
        ("ae", "United Arab Emirates"),
        ("ye", "Yemen"),
        ]),
    "Central Asia": atapi.DisplayList([
        ("io", "British Indian Ocean Territory"),
        ("kz", "Kazakhstan"),
        ("kg", "Kyrgyzstan"),
        ("tj", "Tajikistan"),
        ("tm", "Turkmenistan"),
        ("uz", "Uzbekistan"),
        ]),
    "South Asia": atapi.DisplayList([
        ("af", "Afghanistan"),
        ("bd", "Bangladesh"),
        ("bt", "Bhutan"),
        ("in", "India"),
        ("mv", "Maldives"),
        ("np", "Nepal"),
        ("pk", "Pakistan"),
        ("lk", "Sri Lanka"),
        ]),
    "South East Asia": atapi.DisplayList([
        ("bn", "Brunei Darussalam"),
        ("kh", "Cambodia"),
        ("id", "Indonesia"),
        ("la", "Lao People's Democratic Republic"),
        ("my", "Malaysia"),
        ("mm", "Myanmar"),
        ("ph", "Philippines"),
        ("sg", "Singapore"),
        ("th", "Thailand"),
        ("tl", "Timor-Leste"),
        ("vn", "Viet Nam"),
        ]),
    "North East Asia": atapi.DisplayList([
        ("cn", "China"),
        ("hk", "Hong Kong"),
        ("jp", "Japan"),
        ("kp", "Korea, Democratic People's Republic Of"),
        ("kr", "Korea, Republic Of"),
        ("mo", "Macau"),
        ("mn", "Mongolia"),
        ("tw", "Taiwan"),
        ]),
    "Australasia": atapi.DisplayList([
        ("as", "American Samoa"),
        ("aq", "Antarctica"),
        ("au", "Australia"),
        ("cx", "Christmas Island"),
        ("cc", "Cocos (Keeling) Islands"),
        ("ck", "Cook Islands"),
        ("fj", "Fiji"),
        ("pf", "French Polynesia"),
        ("gu", "Guam"),
        ("hm", "Heard And Mc Donald Islands"),
        ("ki", "Kiribati"),
        ("mh", "Marshall Islands"),
        ("fm", "Micronesia, Federated States Of"),
        ("nr", "Nauru"),
        ("nc", "New Caledonia"),
        ("nz", "New Zealand"),
        ("nu", "Niue"),
        ("nf", "Norfolk Island"),
        ("mp", "Northern Mariana Islands"),
        ("pw", "Palau"),
        ("pg", "Papua New Guinea"),
        ("pn", "Pitcairn"),
        ("ws", "Samoa"),
        ("sb", "Solomon Islands"),
        ("tk", "Tokelau"),
        ("to", "Tonga"),
        ("tv", "Tuvalu"),
        ("vu", "Vanuatu"),
        ("wf", "Wallis And Futuna Islands"),
        ]),
    "Caribbean": atapi.DisplayList([
        ("ai", "Anguilla"),
        ("ag", "Antigua And Barbuda"),
        ("aw", "Aruba"),
        ("bs", "Bahamas"),
        ("bb", "Barbados"),
        ("bm", "Bermuda"),
        ("ky", "Cayman Islands"),
        ("cu", "Cuba"),
        ("dm", "Dominica"),
        ("do", "Dominican Republic"),
        ("gd", "Grenada"),
        ("gp", "Guadeloupe"),
        ("ht", "Haiti"),
        ("jm", "Jamaica"),
        ("mq", "Martinique"),
        ("ms", "Montserrat"),
        ("an", "Netherlands Antilles"),
        ("pr", "Puerto Rico"),
        ("kn", "Saint Kitts And Nevis"),
        ("lc", "Saint Lucia"),
        ("vc", "Saint Vincent And The Grenadines"),
        ("tt", "Trinidad And Tobago"),
        ("tc", "Turks And Caicos Islands"),
        ("vg", "Virgin Islands (British)"),
        ("vi", "Virgin Islands (U.S.)"),
        ]),
    "Africa": atapi.DisplayList([
        ("dz", "Algeria"),
        ("ao", "Angola"),
        ("bj", "Benin"),
        ("bw", "Botswana"),
        ("bv", "Bouvet Island"),
        ("bf", "Burkina Faso"),
        ("bi", "Burundi"),
        ("cm", "Cameroon"),
        ("cv", "Cape Verde"),
        ("cf", "Central African Republic"),
        ("td", "Chad"),
        ("km", "Comoros"),
        ("cd", "Congo, Democratic Republic Of (Was Zaire)"),
        ("cg", "Congo, People's Republic Of"),
        ("ci", "Cote D'ivoire"),
        ("dj", "Djibouti"),
        ("eg", "Egypt"),
        ("gq", "Equatorial Guinea"),
        ("er", "Eritrea"),
        ("et", "Ethiopia"),
        ("tf", "French Southern Territories"),
        ("ga", "Gabon"),
        ("gm", "Gambia"),
        ("gh", "Ghana"),
        ("gn", "Guinea"),
        ("gw", "Guinea-Bissau"),
        ("ke", "Kenya"),
        ("ls", "Lesotho"),
        ("lr", "Liberia"),
        ("ly", "Libyan Arab Jamahiriya"),
        ("mg", "Madagascar"),
        ("mw", "Malawi"),
        ("ml", "Mali"),
        ("mr", "Mauritania"),
        ("mu", "Mauritius"),
        ("yt", "Mayotte"),
        ("ma", "Morocco"),
        ("mz", "Mozambique"),
        ("na", "Namibia"),
        ("ne", "Niger"),
        ("ng", "Nigeria"),
        ("re", "Reunion"),
        ("rw", "Rwanda"),
        ("st", "Sao Tome And Principe"),
        ("sn", "Senegal"),
        ("sc", "Seychelles"),
        ("sl", "Sierra Leone"),
        ("so", "Somalia"),
        ("za", "South Africa"),
        ("sh", "St. Helena"),
        ("sd", "Sudan"),
        ("sz", "Swaziland"),
        ("tz", "Tanzania, United Republic Of"),
        ("tg", "Togo"),
        ("tn", "Tunisia"),
        ("ug", "Uganda"),
        ("eh", "Western Sahara"),
        ("zm", "Zambia"),
        ("zw", "Zimbabwe"),
        ]),
    }

vocab = countries.values()[0]
for dl in countries.values()[1:]:
    vocab += dl
