r"""Auto generated by mod2doctest on 2009-11-09 08:29:31.834000:

Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from mod2doctest import m2d_print


===============================================================================
TEST_SETUP
===============================================================================
>>> import pickle
>>> import os


===============================================================================
TEST_TEARDOWN
===============================================================================
>>> import sys
>>> del sys.modules['pickle']
>>> print sys.modules.keys()
['_bisect', 'functools', 'random', 'heapq', 'subprocess', 'gc', 'encodings.encodings', 'msvcrt', 'struct', 'tempfile', 'pprint', 'imp', 'collections', 'mod2doctest.datetime', 'zipimport', 'string', 'repr', 'datetime', 'bisect', 'signal', 'cmd', 'threading', 'token', 'dis', 'cStringIO', 'locale', 'encodings', 'abc', 'bdb', '_subprocess', 're', 'ntpath', 'mod2doctest.os', 'math', 'UserDict', 'inspect', 'mod2doctest.inspect', 'codecs', '_functools', '_locale', 'mod2doctest', 'thread', 'StringIO', 'traceback', 'mod2doctest.mod2doctest', 'itertools', 'opcode', 'doctest', 'os', 'pdb', 'mod2doctest.sys', '__future__', '_collections', '_sre', 'unittest', '__builtin__', 'operator', '_heapq', 'errno', 'binascii', 'sre_constants', 'os.path', 'tokenize', '_warnings', 'encodings.__builtin__', '_codecs', 'encodings.cp1252', '_struct', 'keyword', 'mod2doctest.subprocess', 'encodings.aliases', 'exceptions', 'sre_parse', 'copy_reg', 'sre_compile', '_random', 'site', 'getpass', '__main__', 'strop', 'encodings.codecs', '_abcoll', 'nt', 'genericpath', 'stat', 'warnings', 'mod2doctest.doctest', 'sys', 'types', 'difflib', 'marshal', 'linecache', 'time', 'mod2doctest.re']


GOING TO DO IT
-------------------------------------------------------------------------------
>>> print 'foobar'
foobar


GOING TO DO IT
-------------------------------------------------------------------------------
>>> print 'baz'
baz


>>> m2d_print.h3('NOW YOU WILL SEE IT')
NOW YOU WILL SEE IT
>>> print 'foobarbaz'
foobarbaz

"""

if __name__ == '__main__':
    import doctest
    doctest.testmod(optionflags=524)

