// JP lang variables

tinyMCE.addToLang('',{
theme_style_select : 'スタイル',
theme_paragraph : '文脈',
theme_address : 'アドレス',
theme_pre : '整形済み',
theme_h1 : 'H1',
theme_h2 : 'H2',
theme_h3 : 'H3',
theme_h4 : 'H4',
theme_h5 : 'H5',
theme_h6 : 'H6',
theme_div : 'Div',
insert_anchor_title : 'アンカーの挿入/編集',
insert_anchor_name : 'アンカーの名前',
theme_anchor_desc : 'アンカーの挿入/編集',
theme_code_desc : 'HTMLの直接編集',
theme_code_title : 'HTMLの編集',
theme_code_wordwrap : 'Word wrap',
theme_hr_desc : '水平線',
theme_removeformat_desc : '整形情報削除',
theme_visualaid_desc : '補助情報の視覚化(トグル)',
theme_sub_desc : '添字下',
theme_sup_desc : '添字上',
theme_charmap_desc : '特殊文字の入力',
theme_charmap_title : '特殊文字を選択して下さい',
insert_image_dimensions : '大きさ指定',
insert_image_border : '境界幅',
insert_image_vspace : '縦余白',
insert_image_hspace : '横余白',
insert_image_align : '位置合わせ',
insert_image_align_default : '暗黙',
insert_image_align_baseline : '基準線',
insert_image_align_top : '上',
insert_image_align_middle : '中',
insert_image_align_bottom : '下',
insert_image_align_texttop : '文字の上',
insert_image_align_absmiddle : '絶対に中',
insert_image_align_absbottom : '絶対に下',
insert_image_align_left : '左',
insert_image_align_right : '右',
theme_font_size : '-- Font size --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_colorpicker_title : '色の選択',
theme_colorpicker_apply : '適用',
theme_forecolor_desc : '文字色',
theme_backcolor_desc : 'Select background color',
theme_clipboard_msg : 'Copy/Cut/Paste is not available in Mozilla and Firefox.\nDo you want more information about this issue?',
theme_path : 'Path',
cut_desc : 'Cut',
copy_desc : 'Copy',
paste_desc : 'Paste',
link_list : 'Link list',
image_list : 'Image list',
browse : 'Browse',
image_props_desc : 'Image properties',
newdocument_desc : 'New document',
class_name : 'クラス',
newdocument : 'Are you sure you want clear all contents?'
});
