# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conflicts_dialog.ui'
#
# Created: Wed Jun 29 15:29:02 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(991, 698)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/gitbuster_logo.xcf"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.conflictDetailsGridLayout = QtGui.QGridLayout(self.frame)
        self.conflictDetailsGridLayout.setObjectName("conflictDetailsGridLayout")
        self.diffTextEdit = QtGui.QTextEdit(self.frame)
        self.diffTextEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.diffTextEdit.setFont(font)
        self.diffTextEdit.setReadOnly(True)
        self.diffTextEdit.setObjectName("diffTextEdit")
        self.conflictDetailsGridLayout.addWidget(self.diffTextEdit, 4, 0, 1, 3)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.conflictDetailsGridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.conflictDetailsGridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.conflictDetailsGridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.conflictDetailsGridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.deleteRadioButton = QtGui.QRadioButton(self.frame)
        self.deleteRadioButton.setObjectName("deleteRadioButton")
        self.conflictDetailsGridLayout.addWidget(self.deleteRadioButton, 8, 0, 1, 2)
        self.addRadioButton = QtGui.QRadioButton(self.frame)
        self.addRadioButton.setObjectName("addRadioButton")
        self.conflictDetailsGridLayout.addWidget(self.addRadioButton, 9, 0, 1, 2)
        self.addCustomRadioButton = QtGui.QRadioButton(self.frame)
        self.addCustomRadioButton.setObjectName("addCustomRadioButton")
        self.conflictDetailsGridLayout.addWidget(self.addCustomRadioButton, 10, 0, 1, 2)
        self.filepathLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filepathLabel.setFont(font)
        self.filepathLabel.setObjectName("filepathLabel")
        self.conflictDetailsGridLayout.addWidget(self.filepathLabel, 0, 1, 1, 1)
        self.conflictTextEdit = QtGui.QTextEdit(self.frame)
        self.conflictTextEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.conflictTextEdit.setFont(font)
        self.conflictTextEdit.setReadOnly(False)
        self.conflictTextEdit.setObjectName("conflictTextEdit")
        self.conflictDetailsGridLayout.addWidget(self.conflictTextEdit, 6, 0, 1, 3)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.conflictDetailsGridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.noneRadioButton = QtGui.QRadioButton(self.frame)
        self.noneRadioButton.setObjectName("noneRadioButton")
        self.conflictDetailsGridLayout.addWidget(self.noneRadioButton, 11, 0, 1, 2)
        self.origTextEdit = QtGui.QTextEdit(self.frame)
        self.origTextEdit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        self.origTextEdit.setFont(font)
        self.origTextEdit.setReadOnly(True)
        self.origTextEdit.setObjectName("origTextEdit")
        self.conflictDetailsGridLayout.addWidget(self.origTextEdit, 2, 0, 1, 3)
        self.conflictDetailsGridLayout.setColumnStretch(1, 10)
        self.conflictDetailsGridLayout.setRowStretch(2, 1)
        self.conflictDetailsGridLayout.setRowStretch(4, 1)
        self.conflictDetailsGridLayout.setRowStretch(6, 2)
        self.gridLayout.addWidget(self.frame, 0, 1, 1, 5)
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 3)
        self.treeWidget = QtGui.QTreeWidget(Dialog)
        self.treeWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 0, 0, 1, 1)
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 5, 1, 1)
        self.applySolutionsButton = QtGui.QPushButton(Dialog)
        self.applySolutionsButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.applySolutionsButton.setObjectName("applySolutionsButton")
        self.gridLayout.addWidget(self.applySolutionsButton, 1, 4, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL("clicked()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "gitbuster - Conflicts mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Unmerged state", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Diff that should be applied by the commit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "State before picking the commit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Resolve by :", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRadioButton.setText(QtGui.QApplication.translate("Dialog", "Deleting the file", None, QtGui.QApplication.UnicodeUTF8))
        self.addRadioButton.setText(QtGui.QApplication.translate("Dialog", "Adding the file", None, QtGui.QApplication.UnicodeUTF8))
        self.addCustomRadioButton.setText(QtGui.QApplication.translate("Dialog", "Adding the file with a custom content", None, QtGui.QApplication.UnicodeUTF8))
        self.filepathLabel.setText(QtGui.QApplication.translate("Dialog", "filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Unmerged file :", None, QtGui.QApplication.UnicodeUTF8))
        self.noneRadioButton.setText(QtGui.QApplication.translate("Dialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("Dialog", "Unmerged files", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.applySolutionsButton.setText(QtGui.QApplication.translate("Dialog", "Apply solutions", None, QtGui.QApplication.UnicodeUTF8))

import gitbuster_rc
