#Autogenerated in astropysics setup.py on 2010-10-11 00:13:46.800558
#these components can be changed for new versions
version = '0.1.dev-r815'

major = 0
minor = 1
bugfix = None
dev = True

release = not dev
