BASE_AT_PROPERTIES = dict(title='title',
                               description='description',
                               text='text',
                               subject='subject',
                               relatedItems='relatedItems',
                               location='location',
                               language='language',
                               effectiveDate='effectiveDate',
                               expirationDate='expirationDate',
                               creation_date='creation_date',
                               modification_date='modification_date',
                               creators='creators',
                               contributors='contributors',
                               rights='rights',
                               allowDiscussion='allowDiscussion',
                               excludeFromNav='excludeFromNav')