#This file was originally generated by PyScripter's unitest wizard

import unittest
import ui

class TestRedirectText(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testwrite(self):
        pass

class TestMyFileDropTarget(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnDropFiles(self):
        pass

class TestNoteTab(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvtCheckBox(self):
        pass

    def testOnFileButton(self):
        pass

    def testOnDirButton(self):
        pass

class TestMyHtmlWindow(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

class TestContentFrame(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

class TestMyPanel(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEvtCheckBox1(self):
        pass

    def testEvtCheckBox2(self):
        pass

    def testOnPageChanged(self):
        pass

    def testEvtRadioBox(self):
        pass

    def testEvtRadioBox2(self):
        pass

    def testOnSyll(self):
        pass

    def testOnQuit(self):
        pass

    def testOnDemo(self):
        pass

    def testOnReload(self):
        pass

    def testbuttonData(self):
        pass

    def testcreateButtonBar(self):
        pass

    def testbuildOneButton(self):
        pass

class TestMyFrame(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnMenu(self):
        pass

    def testmenuData(self):
        pass

    def testcreateMenuBar(self):
        pass

    def testcreateMenu(self):
        pass

    def testcreateHelpBar(self):
        pass

    def testerrDial(self):
        pass

    def testconf_update(self):
        pass

    def testOnNewS(self):
        pass

    def testOnEditS(self):
        pass

    def testOnLoadS(self):
        pass

    def testOnResetS(self):
        pass

    def testOnQuit(self):
        pass

    def testOnContents(self):
        pass

    def testOnAbout(self):
        pass

class TestMyApp(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOnInit(self):
        pass

class TestGlobalFunctions(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testgetIco(self):
        pass

    def testgetBitmap(self):
        pass

    def testwritefile(self):
        pass

    def testsavedial(self):
        pass

    def testfiledial(self):
        pass

    def testmain(self):
        pass

if __name__ == '__main__':
    unittest.main()
