# -*- coding: utf-8 -*-
#
# Copyright (C) 2010 Roberto Longobardi - seccanj@gmail.com
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#

LABELS = {
    'main_tab_title': "Test Manager",
    'select_cat_to_move': "Select the catalog into which to paste the Test Case and click on 'Move the copied Test Case here'. ",
    'select_cat_to_move2': "Select the catalog (even this one) into which to paste the Test Case and click on 'Move the copied Test Case here'. ",
    'new_catalog': "New Catalog:",
    'add_catalog': "Add a Catalog",
    'new_subcatalog': "New Sub-Catalog:",
    'add_subcatalog': "Add a Sub-Catalog",
    'move_here': "Move the copied Test Case here",
    'move_tc_help_msg': "The Test Case has been copied. Now select the catalog into which to move the Test Case and click on 'Move the copied Test Case here'. ",
    'cancel': "Cancel",
    'move_tc_button': "Move the Test Case into another catalog",
    'test_case': "Test Case",
    'open_ticket_button': "Open a Ticket on this Test Case",
    'add_tc_button': "Add a Test Case",
    'new_tc_label': "New Test Case:",
    'tc_list': "Test Catalogs List",
    'tc_catalog': "Test Catalog",
    'all_catalogs': "All Catalogs",
    'filter_label': "Filter:",
    'filter_help': "Type the test to search for, even more than one word. You can also filter on the test case status (untested, successful, failed).",
    'expand_all': "Expand all",
    'collapse_all': "Collapse all",
    'SUCCESSFUL': "Successful",
    'FAILED': "Failed",
    'TO_BE_TESTED': "Untested",
    'change_status_label': "Change the Status:",
    'status_change_hist': "Status change history",
    'open': "Open",
    'timestamp': "Timestamp",
    'author': "Author",
    'status': "Status",
    'new_plan_label': "New Test Plan:",
    'add_test_plan_button': "Generate a new Test Plan",
    'test_plan': "Test Plan: ",
    'back_to_catalog': "Back to the Catalog",
    'back_to_plan': "Back to the Test Plan",
    'regenerate_plan_button': "Regenerate Test Plan",
    'test_plan_list': "Available Test Plans",
    'plan_name': "Plan Name",
    'open_testplan_title': "Open Test Plan",
    'duplicate_tc_button': "Duplicate the Test Case",
    'edit_test_case_label': "Edit the Test Case",
    'edit_label': "Edit",
    'update_button': "Save",
    'name_header': "Name",
    'id_header': "ID",
    'description_header': "Description",
    'last_change_header': "Last Change",
    'delete': "Delete",
    'duplicate_catalog': "Duplicate the Catalog"
}
