from pymorphous import *

print SIMULATOR_RUNTIME_CONSTANTS
print SIMULATOR_RUNTIME_DEFAULTS
print SIMULATOR_GRAPHICS_DEFAULTS

SIMULATOR_RUNTIME_DEFAULTS.USE_GRAPHICS = "foobar"

print SIMULATOR_RUNTIME_DEFAULTS