# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gitbuster/main_window.ui'
#
# Created: Mon Feb 28 18:13:57 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(860, 810)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.checkboxLayout = QtGui.QGridLayout()
        self.checkboxLayout.setObjectName("checkboxLayout")
        self.gridLayout.addLayout(self.checkboxLayout, 0, 0, 1, 3)
        self.tableView = QtGui.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableView, 2, 0, 1, 3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mergeCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.mergeCheckBox.setChecked(True)
        self.mergeCheckBox.setObjectName("mergeCheckBox")
        self.gridLayout_2.addWidget(self.mergeCheckBox, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(37, 18, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.applyButton = QtGui.QPushButton(self.centralwidget)
        self.applyButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.applyButton.setObjectName("applyButton")
        self.gridLayout_3.addWidget(self.applyButton, 0, 2, 1, 1)
        self.cancelButton = QtGui.QPushButton(self.centralwidget)
        self.cancelButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_3.addWidget(self.cancelButton, 0, 3, 1, 1)
        self.toggleModificationsButton = QtGui.QPushButton(self.centralwidget)
        self.toggleModificationsButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.toggleModificationsButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toggleModificationsButton.setObjectName("toggleModificationsButton")
        self.gridLayout_3.addWidget(self.toggleModificationsButton, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(43, 22, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 8, 0, 1, 3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.currentBranchLabel = QtGui.QLabel(self.centralwidget)
        self.currentBranchLabel.setObjectName("currentBranchLabel")
        self.gridLayout_5.addWidget(self.currentBranchLabel, 0, 0, 1, 1)
        self.currentBranchComboBox = QtGui.QComboBox(self.centralwidget)
        self.currentBranchComboBox.setMinimumSize(QtCore.QSize(80, 0))
        self.currentBranchComboBox.setMaximumSize(QtCore.QSize(160, 16777215))
        self.currentBranchComboBox.setObjectName("currentBranchComboBox")
        self.gridLayout_5.addWidget(self.currentBranchComboBox, 0, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.filtersLayout = QtGui.QGridLayout()
        self.filtersLayout.setObjectName("filtersLayout")
        self.beforeDateFilterDateEdit = QtGui.QDateEdit(self.tab)
        self.beforeDateFilterDateEdit.setObjectName("beforeDateFilterDateEdit")
        self.filtersLayout.addWidget(self.beforeDateFilterDateEdit, 1, 1, 1, 1)
        self.afterWeekdayFilterComboBox = QtGui.QComboBox(self.tab)
        self.afterWeekdayFilterComboBox.setObjectName("afterWeekdayFilterComboBox")
        self.afterWeekdayFilterComboBox.addItem("")
        self.afterWeekdayFilterComboBox.addItem("")
        self.afterWeekdayFilterComboBox.addItem("")
        self.afterWeekdayFilterComboBox.addItem("")
        self.afterWeekdayFilterComboBox.addItem("")
        self.afterWeekdayFilterComboBox.addItem("")
        self.afterWeekdayFilterComboBox.addItem("")
        self.filtersLayout.addWidget(self.afterWeekdayFilterComboBox, 2, 1, 1, 1)
        self.beforeWeekdayFilterComboBox = QtGui.QComboBox(self.tab)
        self.beforeWeekdayFilterComboBox.setObjectName("beforeWeekdayFilterComboBox")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.beforeWeekdayFilterComboBox.addItem("")
        self.filtersLayout.addWidget(self.beforeWeekdayFilterComboBox, 3, 1, 1, 1)
        self.afterWeekdayFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.afterWeekdayFilterCheckBox.setObjectName("afterWeekdayFilterCheckBox")
        self.filtersLayout.addWidget(self.afterWeekdayFilterCheckBox, 2, 0, 1, 1)
        self.beforeDateFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.beforeDateFilterCheckBox.setObjectName("beforeDateFilterCheckBox")
        self.filtersLayout.addWidget(self.beforeDateFilterCheckBox, 1, 0, 1, 1)
        self.beforeWeekdayFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.beforeWeekdayFilterCheckBox.setObjectName("beforeWeekdayFilterCheckBox")
        self.filtersLayout.addWidget(self.beforeWeekdayFilterCheckBox, 3, 0, 1, 1)
        self.commitFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.commitFilterCheckBox.setObjectName("commitFilterCheckBox")
        self.filtersLayout.addWidget(self.commitFilterCheckBox, 3, 2, 1, 2)
        self.beforeHourFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.beforeHourFilterCheckBox.setObjectName("beforeHourFilterCheckBox")
        self.filtersLayout.addWidget(self.beforeHourFilterCheckBox, 1, 2, 1, 2)
        self.commitFilterLineEdit = QtGui.QLineEdit(self.tab)
        self.commitFilterLineEdit.setObjectName("commitFilterLineEdit")
        self.filtersLayout.addWidget(self.commitFilterLineEdit, 3, 4, 1, 1)
        self.beforeHourFilterTimeEdit = QtGui.QTimeEdit(self.tab)
        self.beforeHourFilterTimeEdit.setObjectName("beforeHourFilterTimeEdit")
        self.filtersLayout.addWidget(self.beforeHourFilterTimeEdit, 1, 4, 1, 1)
        self.nameEmailFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.nameEmailFilterCheckBox.setObjectName("nameEmailFilterCheckBox")
        self.filtersLayout.addWidget(self.nameEmailFilterCheckBox, 2, 2, 1, 2)
        self.afterHourFilterTimeEdit = QtGui.QTimeEdit(self.tab)
        self.afterHourFilterTimeEdit.setObjectName("afterHourFilterTimeEdit")
        self.filtersLayout.addWidget(self.afterHourFilterTimeEdit, 0, 4, 1, 1)
        self.nameEmailFilterLineEdit = QtGui.QLineEdit(self.tab)
        self.nameEmailFilterLineEdit.setObjectName("nameEmailFilterLineEdit")
        self.filtersLayout.addWidget(self.nameEmailFilterLineEdit, 2, 4, 1, 1)
        self.afterDateFilterDateEdit = QtGui.QDateEdit(self.tab)
        self.afterDateFilterDateEdit.setObjectName("afterDateFilterDateEdit")
        self.filtersLayout.addWidget(self.afterDateFilterDateEdit, 0, 1, 1, 1)
        self.afterDateFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.afterDateFilterCheckBox.setObjectName("afterDateFilterCheckBox")
        self.filtersLayout.addWidget(self.afterDateFilterCheckBox, 0, 0, 1, 1)
        self.afterHourFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.afterHourFilterCheckBox.setObjectName("afterHourFilterCheckBox")
        self.filtersLayout.addWidget(self.afterHourFilterCheckBox, 0, 2, 1, 2)
        self.localOnlyFilterCheckBox = QtGui.QCheckBox(self.tab)
        self.localOnlyFilterCheckBox.setObjectName("localOnlyFilterCheckBox")
        self.filtersLayout.addWidget(self.localOnlyFilterCheckBox, 4, 0, 1, 1)
        self.filtersLayout.setColumnStretch(0, 1)
        self.filtersLayout.setColumnStretch(1, 1)
        self.filtersLayout.setColumnStretch(2, 1)
        self.filtersLayout.setColumnStretch(4, 1)
        self.gridLayout_4.addLayout(self.filtersLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.reOrderLabel = QtGui.QLabel(self.tab_2)
        self.reOrderLabel.setObjectName("reOrderLabel")
        self.gridLayout_6.addWidget(self.reOrderLabel, 0, 0, 1, 2)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.betweenDatesLabel = QtGui.QLabel(self.tab_2)
        self.betweenDatesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.betweenDatesLabel.setObjectName("betweenDatesLabel")
        self.gridLayout_8.addWidget(self.betweenDatesLabel, 0, 0, 1, 1)
        self.reOrderMinDateEdit = QtGui.QDateEdit(self.tab_2)
        self.reOrderMinDateEdit.setObjectName("reOrderMinDateEdit")
        self.gridLayout_8.addWidget(self.reOrderMinDateEdit, 0, 1, 1, 1)
        self.andDatesLabel = QtGui.QLabel(self.tab_2)
        self.andDatesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.andDatesLabel.setObjectName("andDatesLabel")
        self.gridLayout_8.addWidget(self.andDatesLabel, 0, 2, 1, 1)
        self.reOrderMaxDateEdit = QtGui.QDateEdit(self.tab_2)
        self.reOrderMaxDateEdit.setObjectName("reOrderMaxDateEdit")
        self.gridLayout_8.addWidget(self.reOrderMaxDateEdit, 0, 3, 1, 1)
        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 3)
        self.gridLayout_8.setColumnStretch(2, 1)
        self.gridLayout_8.setColumnStretch(3, 3)
        self.gridLayout_6.addLayout(self.gridLayout_8, 3, 1, 1, 1)
        self.reOrderDatesLabel = QtGui.QLabel(self.tab_2)
        self.reOrderDatesLabel.setObjectName("reOrderDatesLabel")
        self.gridLayout_6.addWidget(self.reOrderDatesLabel, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 2, 3, 1)
        self.reOrderPushButton = QtGui.QPushButton(self.tab_2)
        self.reOrderPushButton.setObjectName("reOrderPushButton")
        self.gridLayout_6.addWidget(self.reOrderPushButton, 6, 3, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.betweenHoursLabel = QtGui.QLabel(self.tab_2)
        self.betweenHoursLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.betweenHoursLabel.setObjectName("betweenHoursLabel")
        self.gridLayout_9.addWidget(self.betweenHoursLabel, 0, 0, 1, 1)
        self.reOrderMinTimeEdit = QtGui.QTimeEdit(self.tab_2)
        self.reOrderMinTimeEdit.setObjectName("reOrderMinTimeEdit")
        self.gridLayout_9.addWidget(self.reOrderMinTimeEdit, 0, 1, 1, 1)
        self.andHoursLabel = QtGui.QLabel(self.tab_2)
        self.andHoursLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.andHoursLabel.setObjectName("andHoursLabel")
        self.gridLayout_9.addWidget(self.andHoursLabel, 0, 2, 1, 1)
        self.reOrderMaxTimeEdit = QtGui.QTimeEdit(self.tab_2)
        self.reOrderMaxTimeEdit.setTime(QtCore.QTime(23, 59, 0))
        self.reOrderMaxTimeEdit.setObjectName("reOrderMaxTimeEdit")
        self.gridLayout_9.addWidget(self.reOrderMaxTimeEdit, 0, 3, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 1)
        self.gridLayout_9.setColumnStretch(1, 3)
        self.gridLayout_9.setColumnStretch(2, 1)
        self.gridLayout_9.setColumnStretch(3, 3)
        self.gridLayout_6.addLayout(self.gridLayout_9, 4, 1, 2, 1)
        self.reOrderHoursLabel = QtGui.QLabel(self.tab_2)
        self.reOrderHoursLabel.setObjectName("reOrderHoursLabel")
        self.gridLayout_6.addWidget(self.reOrderHoursLabel, 4, 0, 2, 1)
        self.reOrderWeekdaysLabel = QtGui.QLabel(self.tab_2)
        self.reOrderWeekdaysLabel.setObjectName("reOrderWeekdaysLabel")
        self.gridLayout_6.addWidget(self.reOrderWeekdaysLabel, 2, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.reOrderWeekdayMondayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdayMondayCheckBox.setObjectName("reOrderWeekdayMondayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdayMondayCheckBox, 0, 0, 1, 1)
        self.reOrderWeekdayTuesdayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdayTuesdayCheckBox.setObjectName("reOrderWeekdayTuesdayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdayTuesdayCheckBox, 0, 1, 1, 1)
        self.reOrderWeekdayWednesdayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdayWednesdayCheckBox.setObjectName("reOrderWeekdayWednesdayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdayWednesdayCheckBox, 0, 2, 1, 1)
        self.reOrderWeekdayThursdayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdayThursdayCheckBox.setObjectName("reOrderWeekdayThursdayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdayThursdayCheckBox, 0, 3, 1, 1)
        self.reOrderWeekdayFridayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdayFridayCheckBox.setObjectName("reOrderWeekdayFridayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdayFridayCheckBox, 0, 4, 1, 1)
        self.reOrderWeekdaySaturdayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdaySaturdayCheckBox.setObjectName("reOrderWeekdaySaturdayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdaySaturdayCheckBox, 0, 5, 1, 1)
        self.reOrderWeekdaySundayCheckBox = QtGui.QCheckBox(self.tab_2)
        self.reOrderWeekdaySundayCheckBox.setObjectName("reOrderWeekdaySundayCheckBox")
        self.gridLayout_7.addWidget(self.reOrderWeekdaySundayCheckBox, 0, 6, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 7, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 2, 1, 1, 2)
        self.line = QtGui.QFrame(self.tab_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_6.addWidget(self.line, 1, 0, 1, 4)
        self.reOrderErrorsLabel = QtGui.QLabel(self.tab_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(196, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(196, 0, 3))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.reOrderErrorsLabel.setPalette(palette)
        self.reOrderErrorsLabel.setText("")
        self.reOrderErrorsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reOrderErrorsLabel.setObjectName("reOrderErrorsLabel")
        self.gridLayout_6.addWidget(self.reOrderErrorsLabel, 6, 0, 1, 3)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 5, 0, 1, 3)
        self.gridLayout.setRowStretch(2, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 912, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menuBar)
        self.actionChange_repository = QtGui.QAction(MainWindow)
        self.actionChange_repository.setObjectName("actionChange_repository")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionI_was_never_here = QtGui.QAction(MainWindow)
        self.actionI_was_never_here.setObjectName("actionI_was_never_here")
        self.menuFile.addAction(self.actionChange_repository)
        self.menuFile.addAction(self.actionQuit)
        self.menuOptions.addAction(self.actionI_was_never_here)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.reOrderMinDateEdit, QtCore.SIGNAL("dateChanged(QDate)"), self.reOrderMaxDateEdit.setDate)
        QtCore.QObject.connect(self.reOrderPushButton, QtCore.SIGNAL("clicked()"), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMinDateEdit, QtCore.SIGNAL("dateChanged(QDate)"), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMaxDateEdit, QtCore.SIGNAL("dateChanged(QDate)"), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMaxTimeEdit, QtCore.SIGNAL("timeChanged(QTime)"), self.reOrderErrorsLabel.clear)
        QtCore.QObject.connect(self.reOrderMinTimeEdit, QtCore.SIGNAL("timeChanged(QTime)"), self.reOrderErrorsLabel.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.currentBranchComboBox, self.tableView)
        MainWindow.setTabOrder(self.tableView, self.mergeCheckBox)
        MainWindow.setTabOrder(self.mergeCheckBox, self.afterDateFilterCheckBox)
        MainWindow.setTabOrder(self.afterDateFilterCheckBox, self.afterDateFilterDateEdit)
        MainWindow.setTabOrder(self.afterDateFilterDateEdit, self.afterHourFilterCheckBox)
        MainWindow.setTabOrder(self.afterHourFilterCheckBox, self.afterHourFilterTimeEdit)
        MainWindow.setTabOrder(self.afterHourFilterTimeEdit, self.beforeDateFilterCheckBox)
        MainWindow.setTabOrder(self.beforeDateFilterCheckBox, self.beforeDateFilterDateEdit)
        MainWindow.setTabOrder(self.beforeDateFilterDateEdit, self.beforeHourFilterCheckBox)
        MainWindow.setTabOrder(self.beforeHourFilterCheckBox, self.beforeHourFilterTimeEdit)
        MainWindow.setTabOrder(self.beforeHourFilterTimeEdit, self.afterWeekdayFilterCheckBox)
        MainWindow.setTabOrder(self.afterWeekdayFilterCheckBox, self.afterWeekdayFilterComboBox)
        MainWindow.setTabOrder(self.afterWeekdayFilterComboBox, self.nameEmailFilterCheckBox)
        MainWindow.setTabOrder(self.nameEmailFilterCheckBox, self.nameEmailFilterLineEdit)
        MainWindow.setTabOrder(self.nameEmailFilterLineEdit, self.beforeWeekdayFilterCheckBox)
        MainWindow.setTabOrder(self.beforeWeekdayFilterCheckBox, self.beforeWeekdayFilterComboBox)
        MainWindow.setTabOrder(self.beforeWeekdayFilterComboBox, self.commitFilterCheckBox)
        MainWindow.setTabOrder(self.commitFilterCheckBox, self.commitFilterLineEdit)
        MainWindow.setTabOrder(self.commitFilterLineEdit, self.localOnlyFilterCheckBox)
        MainWindow.setTabOrder(self.localOnlyFilterCheckBox, self.reOrderWeekdayMondayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayMondayCheckBox, self.reOrderWeekdayTuesdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayTuesdayCheckBox, self.reOrderWeekdayWednesdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayWednesdayCheckBox, self.reOrderWeekdayThursdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayThursdayCheckBox, self.reOrderWeekdayFridayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdayFridayCheckBox, self.reOrderWeekdaySaturdayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdaySaturdayCheckBox, self.reOrderWeekdaySundayCheckBox)
        MainWindow.setTabOrder(self.reOrderWeekdaySundayCheckBox, self.reOrderMinDateEdit)
        MainWindow.setTabOrder(self.reOrderMinDateEdit, self.reOrderMaxDateEdit)
        MainWindow.setTabOrder(self.reOrderMaxDateEdit, self.reOrderMinTimeEdit)
        MainWindow.setTabOrder(self.reOrderMinTimeEdit, self.reOrderMaxTimeEdit)
        MainWindow.setTabOrder(self.reOrderMaxTimeEdit, self.reOrderPushButton)
        MainWindow.setTabOrder(self.reOrderPushButton, self.toggleModificationsButton)
        MainWindow.setTabOrder(self.toggleModificationsButton, self.applyButton)
        MainWindow.setTabOrder(self.applyButton, self.cancelButton)
        MainWindow.setTabOrder(self.cancelButton, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "gitbuster", None, QtGui.QApplication.UnicodeUTF8))
        self.mergeCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Merge Committed and Authored notions (advised)", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setText(QtGui.QApplication.translate("MainWindow", "&Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.applyButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+A", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.toggleModificationsButton.setText(QtGui.QApplication.translate("MainWindow", "&Hide modifications", None, QtGui.QApplication.UnicodeUTF8))
        self.currentBranchLabel.setText(QtGui.QApplication.translate("MainWindow", "Current branch :", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeDateFilterDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tuedsay", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tuedsay", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.afterWeekdayFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "After weekday", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeDateFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Before date (dd/mm/yyyy)", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeWeekdayFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Before weekday", None, QtGui.QApplication.UnicodeUTF8))
        self.commitFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Match commit message", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeHourFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Before hour", None, QtGui.QApplication.UnicodeUTF8))
        self.beforeHourFilterTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.nameEmailFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Match name/email", None, QtGui.QApplication.UnicodeUTF8))
        self.afterHourFilterTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.afterDateFilterDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.afterDateFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "After date (dd/mm/yyyy)", None, QtGui.QApplication.UnicodeUTF8))
        self.afterHourFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "After hour", None, QtGui.QApplication.UnicodeUTF8))
        self.localOnlyFilterCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Local commits only", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderLabel.setText(QtGui.QApplication.translate("MainWindow", "Re-order the displayed commits ", None, QtGui.QApplication.UnicodeUTF8))
        self.betweenDatesLabel.setText(QtGui.QApplication.translate("MainWindow", "between:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMinDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.andDatesLabel.setText(QtGui.QApplication.translate("MainWindow", "and:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMaxDateEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderDatesLabel.setText(QtGui.QApplication.translate("MainWindow", "Dates:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderPushButton.setText(QtGui.QApplication.translate("MainWindow", "Re-order", None, QtGui.QApplication.UnicodeUTF8))
        self.betweenHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "between:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMinTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.andHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "and:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderMaxTimeEdit.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "hh:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "Hours:", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdaysLabel.setText(QtGui.QApplication.translate("MainWindow", "Weekdays :", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayMondayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Monday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayTuesdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Tuesday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayWednesdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Wednesday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayThursdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Thursday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdayFridayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Friday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdaySaturdayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Saturday", None, QtGui.QApplication.UnicodeUTF8))
        self.reOrderWeekdaySundayCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Sunday", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "(can be left blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Auto re-order", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "&Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChange_repository.setText(QtGui.QApplication.translate("MainWindow", "Change &repository", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionI_was_never_here.setText(QtGui.QApplication.translate("MainWindow", "&I was never here", None, QtGui.QApplication.UnicodeUTF8))

