#Autogenerated in astropysics setup.py on 2011-03-18 11:57:58.227128
#these components can be changed for new versions
version = '0.1.dev-r1020'

major = 0
minor = 1
bugfix = None
dev = True

release = not dev
