#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'1.00',
 'build_date': '2010-04-08 16:05:23 -0700',
 'clean': None,
 'date': '2010-04-08 16:04:43 -0700',
 'revision_id': 'root@peacemaker-20100408230443-ed8l1fetj9cl7nfg',
 'revno': 751}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
