BROWSERS = [
    ("isWebKit","WebKit"),
    ("isOpera","Opera"),
    ("isChrome","Chrome"),
    ("isSafari","Safari"),
    ("isSafari3","Safari 3"),
    ("isSafari4","Safari 4"),
    ("isIE","IE"),
    ("isIE7","IE 7"),
    ("isIE8","IE 8"),
    ("isIE6","IE 6"),
    ("isGecko","Gecko"),
    ("isGecko2","Gecko 2"),
    ("isGecko3","Gecko 3"),
    ("isFirefox","Firefox"),
    ("isFirefox1","Firefox 1"),
    ("isFirefox2","Firefox 2"),
    ("isFirefox3","Firefox 3"),
    ("isSafariOnMac","Safari on Mac"),
    ("isSafariOnWin","Safari on Win"),
    ("isGeckoOnMac","Gecko on Mac"),
    ("isGeckoOnLinux","Gecko on Linux"),
    ("isGeckoOnWin","Gecko on Win"),
    ("isFirefoxOnMac","Firefox on Mac"),
    ("isFirefoxOnLinux","Firefox on Linux"),
    ("isFirefoxOnWin","Firefox on Win"),
    ("isOperaOnMac","Opera on Mac"),
    ("isOperaOnLinux","Opera on Linux"),
    ("isOperaOnWin","Opera on Win"),
    ("isChromeOnMac","Chrome on Mac"),
    ("isChromeOnLinux","Chrome on Linux"),
    ("isChromeOnWin","Chrome on Win")
]