#Autogenerated in astropysics setup.py on 2010-04-16 12:44:27.204113
#these components can be changed for new versions
version = '0.1.dev-r599'

major = 0
minor = 1
bugfix = None
dev = True

release = not dev
