from zope.i18nmessageid import MessageFactory
raptusContenttemplatesMessageFactory = MessageFactory('raptus.contenttemplates')
from Products.PlacelessTranslationService.utility import PTSTranslationDomain
raptuscontenttemplatesdomain = PTSTranslationDomain('raptus.contenttemplates')