from setuptools import setup, find_packages

setup(
    name = "z3c.extfile",
    version = "0.3.0b2",
    author = "Zope Contributors",
    author_email = "zope3-dev@zope.org",
    description = "Large file handling for zope3",
    license = "ZPL 2.1",
    keywords = "zope3 external file",
    url = 'http://svn.zope.org/z3c.extfile',
    classifiers = [
        'Development Status :: 4 - Beta',
        "License :: OSI Approved :: Zope Public License"],
    packages = find_packages('src'),
    include_package_data = True,
    package_dir = {'':'src'},
    namespace_packages = ['z3c'],
    zip_safe = False,
    extras_require={"test":['zope.testing',
                            'zope.app.testing',
                            'Paste',
                            'PasteDeploy',
                            ]},
    install_requires = ['setuptools',
                        'z3c.filetype',
                        'zope.app.component',
                        'zope.app.appsetup',
                        'zope.app.file',
                        'zope.app.form',
                        'zope.app.wsgi',
                        'zope.cachedescriptors',
                        'zope.contenttype',
                        'zope.datetime',
                        'zope.formlib',
                        'zope.i18nmessageid',
                        'zope.publisher',
                        'zope.schema',
                        'zope.security',
                        'zope.traversing',
                        ],
    )
