# -*- coding: utf-8 -*-
# 
#  setup.py
#  gpalign
#  
#  Created by Lars Yencken on 2009-03-18.
#  Copyright 2009 Lars Yencken. All rights reserved.
# 

from setuptools import setup

VERSION = '0.2.1'

f = file("gpalign/__version__.py", 'w')
f.write('# this file is autogenerated by setup.py\n')
f.write('version = "%s"\n' % VERSION)
f.close()

setup(
    name='gpalign',
    version=VERSION,
    description='Unsupervised grapheme-phoneme aligner for Japanese',
    long_description=\
'An unsupervised grapheme-phoneme aligner for Japanese, designed to align EDICT dictionary entries.',
    author='Lars Yencken',
    author_email='lljy@csse.unimelb.edu.au',
    license='BSD',
    url='http://bitbucket.org/lars512/gpalign-py/',
    packages=['gpalign'],
    setup_requires=['setuptools_hg'],
    install_requires=['cjktools', 'consoleLog>=0.2.4', 'simplestats'],
    scripts=['gpalign/align.py'],
    include_package_data=True,
    zip_safe=False,
)
