#Autogenerated in astropysics setup.py on 2010-11-15 10:53:19.840293
#these components can be changed for new versions
version = '0.1.dev-r886'

major = 0
minor = 1
bugfix = None
dev = True

release = not dev
