COILS_MIMETYPEMAP = { 'txt':  'text/plain',
                      'ldif': 'text/ldif',
                      'pgp':  'application/pgp-encrypted',
                      'gpg':  'application/pgp-encrypted',
                      'pdf':  'application/pdf',
                      'pcl':  'application/vnd.hp-pcl',
                      '123':  'application/vnd.lotus-1-2-3',
                      'wk1':  'application/vnd.lotus-1-2-3',
                      'wk2':  'application/vnd.lotus-1-2-3',
                      'wk3':  'application/vnd.lotus-1-2-3',
                      'wks':  'application/vnd.lotus-1-2-3',
                      'odc':  'application/vnd.oasis.opendocument.chart',
                      'odb':  'application/vnd.oasis.opendocument.database',
                      'odf':  'application/vnd.oasis.opendocument.formula',
                      'odg':  'application/vnd.oasis.opendocument.graphics',
                      'otg':  'application/vnd.oasis.opendocument.graphics-template',
                      'odi':  'application/vnd.oasis.opendocument.image',
                      'odp':  'application/vnd.oasis.opendocument.presentation',
                      'otp':  'application/vnd.oasis.opendocument.presentation-template',
                      'ods':  'application/vnd.oasis.opendocument.spreadsheet',
                      'ots':  'application/vnd.oasis.opendocument.spreadsheet-template',
                      'odt':  'application/vnd.oasis.opendocument.text',
                      'odm':  'application/vnd.oasis.opendocument.text-master',
                      'ott':  'application/vnd.oasis.opendocument.text-template',
                      'oth':  'application/vnd.oasis.opendocument.text-web',
                      'xml':  'text/xml' }