r"""
================================================================================
Auto generated by mod2doctest on 2009-11-09 23:50:55.388000
================================================================================

Python 2.6.2 (r262:71605, Apr 14 2009, 22:40:02) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.


>>> from mod2doctest import m2d_print


===============================================================================
TEST_SETUP
===============================================================================
>>> import pickle
>>> import os


===============================================================================
TEST_TEARDOWN
===============================================================================
>>> import sys
>>> del sys.modules['pickle']
>>> print 'pickle' in sys.modules
False


GOING TO DO IT
-------------------------------------------------------------------------------
>>> print 'foobar'
foobar


GOING TO DO IT
-------------------------------------------------------------------------------
>>> print 'baz'
baz


>>> m2d_print.h3('NOW YOU WILL SEE IT')
NOW YOU WILL SEE IT
>>> print 'foobarbaz'
foobarbaz

"""



from mod2doctest import m2d_print


#===============================================================================
m2d_print.h1('TEST_SETUP')
#===============================================================================
import pickle
import os


#===============================================================================
m2d_print.h1('TEST_TEARDOWN')
#===============================================================================
import sys
del sys.modules['pickle']
print 'pickle' in sys.modules


m2d_print.h2('GOING TO DO IT')
#-------------------------------------------------------------------------------
print 'foobar'


m2d_print.h2('GOING TO DO IT')
#-------------------------------------------------------------------------------
print 'baz'


m2d_print.h3('NOW YOU WILL SEE IT')
print 'foobarbaz'

if __name__ == '__main__':
    import mod2doctest
    mod2doctest.convert(src=None, 
                        target=True, 
                        run_doctest=True)
